volumes:
  accounts-data:
  orders-data:
  eventstore-data:

services:
  db-accounts: &postgres
    image: postgres:17-bookworm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - accounts-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
    command: ["-c", "config_file=/postgresql.conf"]
    ports:
      - 5435:5432

  db-orders:
    <<: *postgres
    volumes:
      - orders-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    ports:
      - 5436:5432

  db-eventstore:
    <<: *postgres
    volumes:
      - eventstore-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    ports:
      - 5437:5432
  accounts:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    depends_on:
      db-accounts:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-accounts:5432/postgres"
    working_dir: /example/apps/accounts
    command: ["bun", "run", "dev"]

  orders:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    depends_on:
      db-orders:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-orders:5432/postgres"
    working_dir: /example/apps/orders
    command: ["bun", "run", "dev"]

  shop:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    working_dir: /example/apps/shop
    command: ["bun", "run", "dev", "--host", "0.0.0.0"]
    depends_on:
      - accounts
      - orders
    ports:
      - 5173:5173

  rejot-sync:
    image: ghcr.io/rejot-dev/rejot-cli:v0.0.10
    depends_on:
      - accounts
      - orders
      - db-eventstore
    command: ["manifest", "sync", "--log-level", "trace", "/example/rejot-manifest.json"]
    volumes:
      - ./:/example
