volumes:
  accounts-data:
  orders-data:
  eventstore-data:

services:
  db-accounts: &postgres
    image: postgres:17-bookworm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - accounts-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
    command: ["-c", "config_file=/postgresql.conf"]
    ports:
      - 5435:5432

  db-orders:
    <<: *postgres
    volumes:
      - orders-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    ports:
      - 5436:5432

  db-eventstore:
    <<: *postgres
    volumes:
      - eventstore-data:/var/lib/postgresql/data
      - ./postgres.conf:/postgresql.conf
    ports:
      - 5437:5432

  bun-init:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    working_dir: /example
    command: ["bun", "install"]

  accounts:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    depends_on:
      bun-init:
        condition: service_completed_successfully
      db-accounts:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-accounts:5432/postgres"
      EVENTSTORE_DATABASE_URL: "postgres://postgres:postgres@db-eventstore:5432/postgres"
    working_dir: /example/apps/accounts
    command: ["bun", "run", "dev"]

  orders:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    depends_on:
      bun-init:
        condition: service_completed_successfully
      db-orders:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-orders:5432/postgres"
      EVENTSTORE_DATABASE_URL: "postgres://postgres:postgres@db-eventstore:5432/postgres"
    working_dir: /example/apps/orders
    command: ["bun", "run", "dev"]

  shop:
    image: oven/bun:1.2.6
    volumes:
      - ./:/example
    working_dir: /example/apps/shop
    command: ["bun", "run", "dev", "--host", "0.0.0.0"]
    depends_on:
      bun-init:
        condition: service_completed_successfully
      accounts:
        condition: service_started
      orders:
        condition: service_started
    ports:
      - 5173:5173

  rejot-sync-from-accounts: &rejot-sync-from-accounts
    image: ghcr.io/rejot-dev/rejot-cli:v0.1.1
    depends_on:
      - accounts
      - orders
      - db-eventstore
    command:
      [
        "manifest",
        "sync",
        "--log-level",
        "trace",
        "/example/rejot-manifest.from-accounts.json",
        "--hostname",
        "0.0.0.0",
        "--api-port",
        "80",
      ]
    volumes:
      - ./:/example

  rejot-sync-to-orders:
    <<: *rejot-sync-from-accounts
    command:
      [
        "manifest",
        "sync",
        "--log-level",
        "trace",
        "/example/rejot-manifest.to-orders.json",
        "/example/rejot-manifest.from-accounts.json",
        "--hostname",
        "0.0.0.0",
        "--api-port",
        "80",
      ]
